### ISSUE TITLE
Send a welcome message for newcomers

### ISSUE THREAD

**Issue by lvndry** [ascension-paris/ascension-discord-bot#4]
It'll be quite helpful to send a private message to newcomers to explain how Discord works
Which channel should be visited first (#roles, #tips, #general) and have a general idea of what this group is about

**Comment by jolepro** [comment]
Actually that functionality is already implemented.
I just have to update the message in order to suit your needs.

It's start at the line 41 of bot,py file and finish at the line 46

**Comment by jolepro** [comment]
Done thanks to your contribution!
